### ISSUE TITLE
eval alias

### ISSUE THREAD

**Issue by izabera** [modernish/modernish#1]
```
	# (Using 'eval' to avoid syntax error in case an alias let='let --' was set above.)
        eval 'let() {
````
eval doesn't prevent alias expansion

**Comment by McDutchie** [comment]
That's true, but you're missing the point. Shells parse the *entire* script, even code that is never executed. If there's even one thing considered an error, even in code that is never executed, then the whole script is refused to run. The only exception to that is code wrapped in 'eval'.

The 'eval' in question is never executed if the alias is defined, so the fact that 'eval' expands aliases is irrelevant here. Instead, the purpose of the 'eval' is to prevent the function definition from being misparsed by the shell in case the alias is defined (remember that it would be parsed without the 'eval' even if it were never actually executed).
