### ISSUE TITLE
Support dynamic function definition without using eval

### ISSUE THREAD

**Issue by tiawl** [modernish/modernish#16]
Hi, I would like to request a feature:

## A simple use case

A user would like to use a queue instead of a stack to work with traps.

## Really simple working solution 1

```
#! /usr/bin/env modernish
#! use safe
#! use var/stack/trap

_pushtrap ()
{
  trapqueue="${CCn}${1}${trapqueue:-${CCn}}"
  trap "${trapqueue}" EXIT DIE
}

_poptrap ()
{
  trapqueue="${trapqueue%${CCn}*${CCn}}${CCn}"
  trap "${trapqueue}" EXIT DIE
}

# Do awesome things with my traps ...
```

### Problems

1) Even if with shell, it is common to deal with global variable this is something that we should avoid if possible. I do not want to have potential variable conflict if I forgot that `trapqueue` is a variable name that I already used here.
2) If a command is using a new line character in your queue, my script is broken. Whatever the character I am using I have to always be aware that I do not use it in a command that I am executing throught my trap queue.
3) The script is not really flexible because it does not trap other signals than EXIT and DIE and there are no possible way to execute different commands between those 2 signals

## A better solution

```
#! /usr/bin/env modernish
#! use safe
#! use var/arith
#! use var/local
#! use var/loop
#! use var/stack/trap

exec 3>&1

_pushtrap ()
{
  if lt ${#} 2; then return 1; fi

  LOCAL cmds="${1}" \
        i
  BEGIN
    shift

    while gt ${#} '0'
    do
      if isset -f mytrap_${1}_0
      then
        i=$(mytrap_${1}_0)
      else
        trap "EXEC_BY_TRAP= mytrap_${1}_0 > /dev/null" ${1}
        i='0'
      fi
      eval "mytrap_${1}_${i} ()
            {
              if isset -f mytrap_${1}_$(( i + 1 ))
              then
                mytrap_${1}_$(( i + 1 ))
              else
                put $(( i + 1 ))
              fi
              if isset -v EXEC_BY_TRAP
              then
                { ${cmds}; } 1>&3
              fi
            }"
      shift
    done
  END
}

_poptrap ()
{
  while gt ${#} '0'
  do
    LOCAL i
    BEGIN
      LOOP for i=0 to $(mytrap_${1}_0) step 1
      DO
        if isset -f mytrap_${1}_${i}
        then
          unset -f mytrap_${1}_${i}
          if isset -f mytrap_${1}_$(( i + 1 ))
          then
            trap "EXEC_BY_TRAP= mytrap_${1}_$(( i + 1 )) > /dev/null" ${1}
          else
            trap '' ${1}
          fi
          break
        fi
      DONE
    END
    shift
  done
}

# Do awesome things with my traps ...
```

Even if this solution is not the best, it is better than the previous one:
- no global variable
- commands in queue are not limited by a character delimiter
- each signal has its own queue

### But ...

We are now using the `eval` command builtin which we do not want to use if possible.

## Suggestion

It could be a great addition if instead of this:

```
      eval "mytrap_${1}_${i} ()
            {
              if isset -f mytrap_${1}_$(( i + 1 ))
              then
                mytrap_${1}_$(( i + 1 ))
              else
                put $(( i + 1 ))
              fi
              if isset -v EXEC_BY_TRAP
              then
                { ${cmds}; } 1>&3
              fi
            }"
```

We could write something like this:

```
      name="mytrap_${1}_${i}"
      body="if isset -f mytrap_${1}_$(( i + 1 ))
            then;
                mytrap_${1}_$(( i + 1 ));
              else
                put $(( i + 1 ));
              fi;
              if isset -v EXEC_BY_TRAP;
              then
                { ${cmds}; } 1>&3;
            fi"

      # suggestion 1:
      define ${name} "${body}"
      # suggestion 2:
      define "${name}(){${body};}"
      # suggestion 3:
      assign -f ${name} "${body}"
      # suggestion 4:
      assign -f "${name}(){${body};}"
``` 

The `var/assign` is a powerful variable-oriented feature provided by `modernish`. But `modernish` misses the function-oriented counterpart. I think that adding a `-f`(unction) option is not a good idea. I prefer adding a new module dedicated for function: using `assign -f -r` does not make sens to me. So writting a dedicated command for function (like `define`) will avoid to manage potential conflicts with `assign` existing options. What do you think ?

**NB:** I did not find a `CONTRIBUTING.md` file. Maybe I am wrong but I do not think that writing this module should be harder than the `var/assign`. If after closing this issue, we agree, I will be glad to be of help and start some work during my freetime if you are busy. But I really need to know what you are expecting when someone is working on `modernish` and how to start. Thank you.

**Comment by McDutchie** [comment]
> The `var/assign` is a powerful variable-oriented feature provided by `modernish`. But `modernish` misses the function-oriented counterpart.

You wouldn't win anything in terms of safety if I implemented that. Why? Consider why using `eval` is considered dangerous: when unvalidated/untrusted values are inserted into code, we have a code injection vulnerability. Values containing `;`, `$(`…`)`, etc. can all be used to execute whatever commands an attacker wants.

With the `assign` function, this is easy to avoid. The assigned value is not shell grammar, so, if we both validate the variable name and make sure the value doesn't get parsed as code at all, the whole thing is perfectly safe.

The proposed `define` function cannot be made safe like that. Both a function name and a function body are code, so must both be parsed by the shell as code. Inserting untrusted and unvalidated values into code is unsafe, even if you don't use `eval` directly.

The resulting false sense of security actually makes things worse. Just using `eval` will at least remind you that you really need to validate whatever values you insert into the code.

Note that modernish has `str isvarname` to easily validate variable/function names.

(By the way, even the `trap` command itself is a form of `eval`; the evaluation/parsing of the trap action is just delayed until the trap is executed. So it can be used unsafely in all the same ways that `eval` can, and often is.)

**Comment by tiawl** [comment]
Thank you for explaining that, I learned a lot.
