### ISSUE TITLE
`${?}` in `trap` is always `0` / `trap` 内で `${?}` が、必ず `0` になる

### ISSUE THREAD

**Issue by qq542vev** [modernish/modernish#21]
nice to meet you. Since I can't read or write English at all, this post is translated from Japanese to English using Google Translate. Therefore, please understand that there may be some poor expressions and sentences that are difficult to read.

Hello modernish developers, I just recently started using modernish and this library is great and easy to use. I hope that you will continue to develop it in the future.

By the way, I discovered a strange phenomenon regarding `trap`. A simple ShellScript like the one below yields `1`.

~~~
#!/usr/bin/env sh
. 'bin/modernish'

trap 'putln "${?}"' 0
exit 1
~~~

However, if you write `use 'var/stack/trap'`, the execution result will be `0`.

~~~
#!/usr/bin/env sh
. 'bin/modernish'

use 'var/stack/trap'
trap 'putln "${?}"' 0 
exit 1
~~~

I suspect this is a bug, what do you think? Or is it the specifications?

------

初めまして。私は英語の読み書きが全くできないため、この投稿はGoogle翻訳を用いて、日本語から英語に翻訳しております。そのため、拙い表現や、読みにくい文章があるかと思われますが、何卒ご了承ください。

modernish の開発者の皆様、こんにちは。私はつい最近 modernish を使い始めたのですが、このライブラリはとても使いやすく素晴らしいです。是非とも今後も開発を継続していただきたいです。

ところで私は `trap` に関する不思議な現象を発見致しました。以下のような単純な ShellScript の実行結果は `1` です。

~~~
#!/usr/bin/env sh
. 'bin/modernish'

trap 'putln "${?}"' 0
exit 1
~~~

ところが `use 'var/stack/trap'` を記載すると実行結果は `0` になります。

~~~
#!/usr/bin/env sh
. 'bin/modernish'

use 'var/stack/trap'
trap 'putln "${?}"' 0 
exit 1
~~~

私はこれについてバグではないかと考えているのですが、如何でしょうか。それとも仕様でしょうか。

**Comment by McDutchie** [comment]
Welcome @qq542vev. The translation is fine, I understand it without any problems. I apologise for taking so much time to respond to your message.

I agree, this is a bug. The patch below should fix it. Please test:

```diff
diff --git a/lib/modernish/mdl/var/stack/trap.mm b/lib/modernish/mdl/var/stack/trap.mm
index eb258c0..c74dbae 100644
--- a/lib/modernish/mdl/var/stack/trap.mm
+++ b/lib/modernish/mdl/var/stack/trap.mm
@@ -540,7 +540,7 @@
 				_Msh_sST_A="${_Msh_sST_A}; case \${_Msh_POSIXtrapERR+s}\${_Msh__V_Msh_trapERR__SP+s} in "
 				_Msh_sST_A="${_Msh_sST_A}('') command trap - ERR;; esac"
 			fi ;;
-		( * )	_Msh_sST_A="_Msh_doTraps $1 $2; eval \"\${_Msh_PT+unset _Msh_PT;\${_Msh_PT}}\"" ;;
+		( * )	_Msh_sST_A="_Msh_doTraps $1 $2; eval \"\${_Msh_PT+unset _Msh_PT;setstatus \$?;\${_Msh_PT}}\"" ;;
 		esac
 		case $1 in
 		( RETURN )
```
