### ISSUE TITLE
Modernish does not install on Termux

### ISSUE THREAD

**Issue by tabbyrobin** [modernish/modernish#23]
This is using release 0.16.5, and also commit 516af140598482fad663fb6a9793df457c773946.

There appear to be at least two issues:

1. `/tmp` is not writeable on Termux. If you try `./install.sh -n`, etc. you get an error that `... /tmp directory not writable`. Workaround: `./install.sh -s bash ...` (For bash, Termux sets TMPDIR env var, e.g. `TMPDIR="/data/data/com.termux/files/usr/tmp"`)
2. `install.sh died: trap: internal error: invalid trap name: 38` Once the tmpdir workaround is used, this second error is encountered.  I have not found a workaround for this error.

**Comment by McDutchie** [comment]
Thanks for the report. Unfortunately I don't currently have access to a Termux environment for testing. Problem 1 can be tested and fixed on any system where I have root access, but for problem 2 it's trickier.

It's unfortunate that /tmp is not writable on Termux; the POSIX standard requires it to be.

**Comment by McDutchie** [comment]
Got termux running now in an emulator in Android Studio for macOS, so I'll try to figure this bug out.

**Comment by tabbyrobin** [comment]
Cool! Let me know if I can be of any help. (Further testing etc.) Trying to
track down the trap 38 error, I used `set -x` and noticed something about
`_Msh_pop_err`...

**Comment by tabbyrobin** [comment]
Cool! Let me know if I can be of any help. (Further testing etc.) Trying to
track down the trap 38 error, I used `set -x` and noticed something about
`_Msh_pop_err`...

**Comment by McDutchie** [comment]
So, that was a bit difficult. Android seems to go out of its way to break POSIX compliance and even basic Unix/Linux assumptions: you cannot read /dev or even /, there is no /tmp, ...

Also, signals are weird; signals 32 through 40 exist but have no names. Again, not a compliant situation. This is how the trap 38 internal error occurred; the `trap` command on bash outputs it as ignored, but it has no name, so it uses the number.

Anyway, I think I've got it sorted now. Commit coming up.

**Comment by McDutchie** [comment]
Now fixed in the master and 0.16 branches. The latter needed an additional fix for /tmp usage in the BUG_APPENDC cap test (no longer supported after 0.16), hence the force-push.

@tabbyrobin, please let me know if this works on your end.

**Comment by tabbyrobin** [comment]
@McDutchie Install successful! Termux 0.118.0. This is awesome, thanks a bunch.
