### ISSUE TITLE
Move share/doc/modernish/examples to share/examples/modernish/

### ISSUE THREAD

**Issue by 0mp** [modernish/modernish#6]
I'm packaging modernish for FreeBSD now. Usually, we put examples under `share/examples/name`, documentation under `share/doc/name` and any other *data*, that do not belong to any of the aforementioned directories, into `share/name`.

I wonder if you'd like to follow the same convention in this repository. 

The reason is that I am not sure if I should move modernish examples to a standard place on FreeBSD or not.

Cheers!

**Comment by 0mp** [comment]
Actually, it would also be nice to be able to just specify the installation directories for docs and examples.

**Comment by McDutchie** [comment]
Neat! However, packaging it is just slightly premature -- I'm just days away from making a first alpha release, I just got a mailing list server up and running and I'm working on the announcement.

I like the `/usr/share/examples` convention, but as far as I know it doesn't really seem to be known on systems other than FreeBSD and NetBSD. I try to follow the [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard). People on non-Free/NetBSD operating systems may not find the examples if they're not somewhere in `/usr/share/doc/modernish`.

The modernish installer is designed to traverse the source directory hierarchy, replicating it in the destination directory with certain modifications – so any options for specifying specific custom directory paths would be a bit of a hack.

So I think it's probably best if your packaging script simply moves the examples directory after running install.sh. Would it be consistent with your policy to leave a symlink behind at the original path, so references in the readme would still be valid?

**Comment by McDutchie** [comment]
Just a heads-up, [0.14.1-alpha](https://github.com/modernish/modernish/releases/tag/v0.14.1-alpha) is out and ready to package.

**Comment by 0mp** [comment]
@McDutchie Nice! I plan to sit back to Modernish soon. Thanks for the update!

**Comment by 0mp** [comment]
> So I think it's probably best if your packaging script simply moves the examples directory after running install.sh. Would it be consistent with your policy to leave a symlink behind at the original path, so references in the readme would still be valid?

I'll have to revisit this bit in the port I think.

**Comment by McDutchie** [comment]
How's the FreeBSD port coming along? At this point it's probably best to package 0.16.1-alpha -- I'm no longer maintaining the 0.14 branch.

**Comment by 0mp** [comment]
I've finally committed the port. I've decided to move examples to ${PREFIX}/share/examples/modernish and leave a symlink to it in share/doc/modernish/examples. That's good enough.

**Comment by McDutchie** [comment]
Nice. https://github.com/freebsd/freebsd-ports/commit/bbc91b69be96cf20b8f5d29e2dd6370eb2909eff

Also, nice there's a resurgence of some interest in modernish! I thought I was the only one left. :)

There have been a few fixes since 0.16.5, I'll have to get an update out soon. The next 0.16 release will be the last as the 0.17.x development series is pretty much ready to become 0.18.0.

**Comment by 0mp** [comment]
> Also, nice there's a resurgence of some interest in modernish! I thought I was the only one left. :)

It is a very interesting project. I read its code from time to time to understand differences between shells.

> There have been a few fixes since 0.16.5, I'll have to get an update out soon. The next 0.16 release will be the last as the 0.17.x development series is pretty much ready to become 0.18.0.

Cool. I'll just update the port when a new release is tagged.
