### ISSUE TITLE
Space won't work as separator in sys/base/tac

### ISSUE THREAD

**Issue by wagnerflo** [modernish/modernish#9]
While looking for a solution how to reverse a list of space separated words I stumbled on ``tac`` and ``sys/base/tac``. On my Linux system:
```shell
~ tac --version
tac (GNU coreutils) 8.32
[...]
~ printf "1 2 3 " | tac -s " "
3 2 1 
```
That's what I would see as expected behavior. But in *modernish* on my FreeBSD 13.0 BETA 1:
```shell
~ which tac
tac not found
~ modernish -c 'use sys/base/tac; printf "1 2 3 " | tac -s " "'
32 1 
~ modernish -c 'use sys/base/tac; printf "1 2 3 " | tac -r -s " "'
3 2 1 
```
Having to turn on regex mode to make that separator work seems like a bug. Other separators also work.
```shell
modernish -c 'use sys/base/tac; printf "1,2,3," | tac -s ","'
3,2,1,
modernish -c 'use sys/base/tac; printf "1\n2\n3\n" | tac
3
2
1
```

**Comment by McDutchie** [comment]
Yes, it's a bug. This is meant to be a compatible replacement for GNU `tac`, except that it uses EREs instead of BREs for regular expression separators (awk cannot work with BREs, or with EREs for that matter, but I wrote a [converter](https://github.com/modernish/modernish/blob/6bf2b5a04de37159ef0582af63fa62ef6494af35/lib/modernish/aux/ematch.awk) that changes EREs to awk REs as they are quite similar).

**Comment by McDutchie** [comment]
The fix for both those cases should be fairly simple: make sure `FS` is always treated as an awk regular expression, which stops `split()` from stripping leading or trailing whitespace.
```diff
--- a/lib/modernish/aux/sys/base/tac.awk
+++ b/lib/modernish/aux/sys/base/tac.awk
@@ -42,11 +42,11 @@ END {
 	FS = ENVIRON["_Msh_tac_s"];
 	if ("_Msh_tac_r" in ENVIRON) {
 		FS = convertere(FS);			# convert POSIX ERE to awk RE (from aux/ematch.awk)
-		if (length(FS) == 1)
-			FS = ("(")(FS)(")");		# force parsing as RE
 	} else {
 		gsub(/[\\.[(*+?{|^$]/, "\\\\&", FS);	# literal FS: escape awk RE characters
 	}
+	if (length(FS) == 1)
+		FS = ("(")(FS)(")");			# force parsing as RE (stops split() stripping whitespace)
 	n = split(text, field);
 
 	# Save each input separator.
```

**Comment by wagnerflo** [comment]
Thank you!
